// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAefIPYuUGjZfi_oR7MadJekCKAu8jVsJY',
    appId: '1:389735548961:android:5025dc6272c460829f3b60',
    messagingSenderId: '389735548961',
    projectId: 'todo-app-496da',
    storageBucket: 'todo-app-496da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUGQ2LyJ2RgRUIT3ZlrFHy8DR_R7mLcJ0',
    appId: '1:389735548961:ios:07f767e6548d4c9b9f3b60',
    messagingSenderId: '389735548961',
    projectId: 'todo-app-496da',
    storageBucket: 'todo-app-496da.appspot.com',
    androidClientId: '389735548961-lg5hmsjtoperq5k76s6ek5ffr4srbblf.apps.googleusercontent.com',
    iosClientId: '389735548961-bca2v5ikaf673739st92qgfa7gv8l6k8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
